### PR TITLE
Move API key for vector tiles into url_params

### LINKED ISSUE #27: Move API Key into url_params
We should update refill to match bubble-wrap's API key usage. https://github.com/tangrams/bubble-wrap/blob/gh-pages/bubble-wrap.yaml#L547

This will make it easier to work with in the iOS/Android SDKs

### PR DESCRIPTION
**Pull request by msmollin**
Fixes #27

### CODE REVIEW

**Comment by nvkelso** [comment]
LGTM.

Before I merge it, what version of Refill do the Android and iOS SDKs use? Is it the default (this file) or one of the `no-labels`, `more-labels` variants (which are derived from this src file)?

Do the SDKs pull from mapzen.com/carto or this repo as a submodule?

**Comment by msmollin** [comment]
@nvkelso Android is pulling from the `no-api-key` branch here: https://github.com/tangrams/refill-style/tree/no-api-key and is using the submodule approach from this repo. 

I'm hoping to just use the gh-pages "master" branch for iOS (thus this change). I have an issue open here: https://github.com/mapzen/ios/issues/64 to determine if cocoapods would make this easier, or stick with a submodule approach for iOS.

**Comment by msmollin** [comment]
I was actually wrong on that, looks like we're actually using more-labels:

https://github.com/mapzen/android/blob/master/.gitmodules

**Comment by nvkelso** [comment]
LGTM

**Pull request merged**
