### PR TITLE
update to v1 vector tiles

### PR DESCRIPTION
**Pull request by sensescape**
- [x] Initial updates
- [x] Make this back to default labels (now is all labels working version)
- [x] Polish updates
- [x] Buildings are sad
- [x] Water boundary is sad
- [x] update source from dev > prod tiles

### CODE REVIEW

**Comment by sensescape** [comment]
@bcamper Any idea why the building are black (should be grey image texture), and the water boundary is black (should be grey)?

sad_buildings

**Comment by bcamper** [comment]
It looks like a regression caused by changes in the way Tangram 0.10 handles material alpha, plus the (unusual) custom shader used in Refill. Bubble Wrap has a different/better solution that works, I'll update Refill in master and we can merge into this branch.

**Comment by bcamper** [comment]
@sensescape should be fixed in this branch now too

**Comment by nvkelso** [comment]
Fixed water boundary in: 493ba2fdfda3de567035640b06544c9ce27fbe4d

**Comment by nvkelso** [comment]
Where "other polish" primarily means:

Generally less filtering by area in POIs layer, but **more filtering** for:
- [x] kind: [garden, allotments]
- [x] kind: [police, fire_station, substation, plant, wastewater_plant, water_works]
- [x] kind: [cafe, restaurant, nursing_home]
- [x] kind: [parking, pedestrian, common, pitch, place_of_worship, playground, school, nursing_home]

**Comment by nvkelso** [comment]
This is ready to be forked off for the **no** and **all** label versions, but waiting on that till everything else settles.

**Pull request merged**
